### ISSUE TITLE
ERROR: XHR failed. Technical details: {"name":"Error","message":"XHR failed"}

### ISSUE THREAD

**Issue by alan-wr** [microsoft/vscode-file-downloader-api#11]
File Downloader extension now active.
Starting download from https://*****.bz2
ERROR: XHR failed. Technical details: {"name":"Error","message":"XHR failed"}

**Comment by daniv-msft** [comment]
Closing this one as a duplicate as it is tracked also in https://github.com/microsoft/vscode-file-downloader/issues/10
