### ISSUE TITLE
Error when trying to get the API

### ISSUE THREAD

**Issue by generalpsycha** [microsoft/vscode-file-downloader-api#12]
Hi,
I'm trying to use this extension to download a file, but I'm already stuck at basic usage.
According to wiki, I should use the following lines:
```
import { Uri } from "vscode";
import { getApi, FileDownloader } from "@microsoft/vscode-file-downloader-api";
```
But the second line causes an error:
**Cannot find module '@microsoft/vscode-file-downloader-api' or its corresponding type declarations.**
Am I doing something wrong?

Regards

**Comment by daniv-msft** [comment]
Hi @generalpsycha,
Could you please:
- Open a command prompt.
- Navigate to the folder corresponding to the root of your VS Code extension (where your `package.json` is).
- Run `npm install @microsoft/vscode-file-downloader-api`

This will update your package.json/package-lock.json files with this NPM package, and you should be good to go.

**Comment by generalpsycha** [comment]
Hi d@daniv-msft,
I tried your solution, and yes, this was exactly the problem. Thank you for your help!
I'm closing the issue.
